# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/csy/Desktop/Study/Logic2024/tetris/tetris/tetris.srcs/sources_1/ip/blk_mem_gen_start/blk_mem_gen_start.xci
# IP: The module: 'blk_mem_gen_start' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/csy/Desktop/Study/Logic2024/tetris/tetris/tetris.gen/sources_1/ip/blk_mem_gen_start/blk_mem_gen_start_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_start'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/csy/Desktop/Study/Logic2024/tetris/tetris/tetris.srcs/sources_1/ip/blk_mem_gen_start/blk_mem_gen_start.xci
# IP: The module: 'blk_mem_gen_start' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/csy/Desktop/Study/Logic2024/tetris/tetris/tetris.gen/sources_1/ip/blk_mem_gen_start/blk_mem_gen_start_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_start'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
